// openconfig.openconfig_example is generated by proto_generator as a protobuf
// representation of a YANG schema.
//
// Input schema modules:
//  - ../api/yang/public/doc/openconfig-example.yang
//  - ../api/yang/public/third_party/ietf/iana-if-type.yang
//  - ../api/yang/public/third_party/ietf/ietf-interfaces.yang
//  - ../api/yang/public/third_party/ietf/ietf-yang-types.yang
//  - ../api/yang/public/third_party/ietf/ietf-inet-types.yang
//  - ../api/yang/public/release/models/bfd/openconfig-bfd.yang
//  - ../api/yang/public/release/models/vlan/openconfig-vlan.yang
//  - ../api/yang/public/release/models/vlan/openconfig-vlan-types.yang
//  - ../api/yang/public/release/models/wifi/openconfig-access-points.yang
//  - ../api/yang/public/release/models/wifi/openconfig-wifi-mac.yang
//  - ../api/yang/public/release/models/wifi/openconfig-wifi-types.yang
//  - ../api/yang/public/release/models/wifi/openconfig-wifi-phy.yang
//  - ../api/yang/public/release/models/wifi/openconfig-ap-interfaces.yang
//  - ../api/yang/public/release/models/wifi/openconfig-ap-manager.yang
//  - ../api/yang/public/release/models/macsec/openconfig-macsec.yang
//  - ../api/yang/public/release/models/macsec/openconfig-macsec-types.yang
//  - ../api/yang/public/release/models/stp/openconfig-spanning-tree-types.yang
//  - ../api/yang/public/release/models/stp/openconfig-spanning-tree.yang
//  - ../api/yang/public/release/models/bgp/openconfig-bgp-errors.yang
//  - ../api/yang/public/release/models/bgp/openconfig-bgp-peer-group.yang
//  - ../api/yang/public/release/models/bgp/openconfig-bgp-types.yang
//  - ../api/yang/public/release/models/bgp/openconfig-bgp-global.yang
//  - ../api/yang/public/release/models/bgp/openconfig-bgp-common.yang
//  - ../api/yang/public/release/models/bgp/openconfig-bgp-neighbor.yang
//  - ../api/yang/public/release/models/bgp/openconfig-bgp-common-structure.yang
//  - ../api/yang/public/release/models/bgp/openconfig-bgp.yang
//  - ../api/yang/public/release/models/bgp/openconfig-bgp-policy.yang
//  - ../api/yang/public/release/models/bgp/openconfig-bgp-common-multiprotocol.yang
//  - ../api/yang/public/release/models/platform/openconfig-platform-types.yang
//  - ../api/yang/public/release/models/platform/openconfig-platform-port.yang
//  - ../api/yang/public/release/models/platform/openconfig-platform-fan.yang
//  - ../api/yang/public/release/models/platform/openconfig-platform-linecard.yang
//  - ../api/yang/public/release/models/platform/openconfig-platform-ext.yang
//  - ../api/yang/public/release/models/platform/openconfig-platform-cpu.yang
//  - ../api/yang/public/release/models/platform/openconfig-platform-psu.yang
//  - ../api/yang/public/release/models/platform/openconfig-platform.yang
//  - ../api/yang/public/release/models/platform/openconfig-platform-transceiver.yang
//  - ../api/yang/public/release/models/multicast/openconfig-pim-types.yang
//  - ../api/yang/public/release/models/multicast/openconfig-igmp-types.yang
//  - ../api/yang/public/release/models/multicast/openconfig-igmp.yang
//  - ../api/yang/public/release/models/multicast/openconfig-pim.yang
//  - ../api/yang/public/release/models/catalog/openconfig-module-catalog.yang
//  - ../api/yang/public/release/models/catalog/openconfig-catalog-types.yang
//  - ../api/yang/public/release/models/interfaces/openconfig-interfaces.yang
//  - ../api/yang/public/release/models/interfaces/openconfig-if-8021x.yang
//  - ../api/yang/public/release/models/interfaces/openconfig-if-types.yang
//  - ../api/yang/public/release/models/interfaces/openconfig-if-aggregate.yang
//  - ../api/yang/public/release/models/interfaces/openconfig-if-poe.yang
//  - ../api/yang/public/release/models/interfaces/openconfig-if-tunnel.yang
//  - ../api/yang/public/release/models/interfaces/openconfig-if-ip.yang
//  - ../api/yang/public/release/models/interfaces/openconfig-if-ethernet.yang
//  - ../api/yang/public/release/models/interfaces/openconfig-if-ethernet-ext.yang
//  - ../api/yang/public/release/models/interfaces/openconfig-if-ip-ext.yang
//  - ../api/yang/public/release/models/acl/openconfig-packet-match-types.yang
//  - ../api/yang/public/release/models/acl/openconfig-packet-match.yang
//  - ../api/yang/public/release/models/acl/openconfig-acl.yang
//  - ../api/yang/public/release/models/system/openconfig-license.yang
//  - ../api/yang/public/release/models/system/openconfig-system.yang
//  - ../api/yang/public/release/models/system/openconfig-aaa-radius.yang
//  - ../api/yang/public/release/models/system/openconfig-aaa.yang
//  - ../api/yang/public/release/models/system/openconfig-system-management.yang
//  - ../api/yang/public/release/models/system/openconfig-aaa-types.yang
//  - ../api/yang/public/release/models/system/openconfig-procmon.yang
//  - ../api/yang/public/release/models/system/openconfig-messages.yang
//  - ../api/yang/public/release/models/system/openconfig-system-terminal.yang
//  - ../api/yang/public/release/models/system/openconfig-system-logging.yang
//  - ../api/yang/public/release/models/system/openconfig-aaa-tacacs.yang
//  - ../api/yang/public/release/models/system/openconfig-alarms.yang
//  - ../api/yang/public/release/models/system/openconfig-alarm-types.yang
//  - ../api/yang/public/release/models/policy/openconfig-policy-types.yang
//  - ../api/yang/public/release/models/policy/openconfig-routing-policy.yang
//  - ../api/yang/public/release/models/lacp/openconfig-lacp.yang
//  - ../api/yang/public/release/models/optical-transport/openconfig-wavelength-router.yang
//  - ../api/yang/public/release/models/optical-transport/openconfig-optical-amplifier.yang
//  - ../api/yang/public/release/models/optical-transport/openconfig-transport-line-protection.yang
//  - ../api/yang/public/release/models/optical-transport/openconfig-channel-monitor.yang
//  - ../api/yang/public/release/models/optical-transport/openconfig-transport-line-connectivity.yang
//  - ../api/yang/public/release/models/optical-transport/openconfig-optical-attenuator.yang
//  - ../api/yang/public/release/models/optical-transport/openconfig-transport-line-common.yang
//  - ../api/yang/public/release/models/optical-transport/openconfig-transport-types.yang
//  - ../api/yang/public/release/models/optical-transport/openconfig-terminal-device.yang
//  - ../api/yang/public/release/models/telemetry/openconfig-telemetry-types.yang
//  - ../api/yang/public/release/models/telemetry/openconfig-telemetry.yang
//  - ../api/yang/public/release/models/openflow/openconfig-openflow.yang
//  - ../api/yang/public/release/models/openflow/openconfig-openflow-types.yang
//  - ../api/yang/public/release/models/rib/openconfig-rib-bgp-tables.yang
//  - ../api/yang/public/release/models/rib/openconfig-rib-bgp-attributes.yang
//  - ../api/yang/public/release/models/rib/openconfig-rib-bgp-ext.yang
//  - ../api/yang/public/release/models/rib/openconfig-rib-bgp-table-attributes.yang
//  - ../api/yang/public/release/models/rib/openconfig-rib-bgp-shared-attributes.yang
//  - ../api/yang/public/release/models/rib/openconfig-rib-bgp-types.yang
//  - ../api/yang/public/release/models/rib/openconfig-rib-bgp.yang
//  - ../api/yang/public/release/models/qos/openconfig-qos-types.yang
//  - ../api/yang/public/release/models/qos/openconfig-qos.yang
//  - ../api/yang/public/release/models/qos/openconfig-qos-elements.yang
//  - ../api/yang/public/release/models/qos/openconfig-qos-interfaces.yang
//  - ../api/yang/public/release/models/policy-forwarding/openconfig-pf-srte.yang
//  - ../api/yang/public/release/models/policy-forwarding/openconfig-pf-forwarding-policies.yang
//  - ../api/yang/public/release/models/policy-forwarding/openconfig-pf-interfaces.yang
//  - ../api/yang/public/release/models/policy-forwarding/openconfig-pf-path-groups.yang
//  - ../api/yang/public/release/models/policy-forwarding/openconfig-policy-forwarding.yang
//  - ../api/yang/public/release/models/relay-agent/openconfig-relay-agent.yang
//  - ../api/yang/public/release/models/lldp/openconfig-lldp.yang
//  - ../api/yang/public/release/models/lldp/openconfig-lldp-types.yang
//  - ../api/yang/public/release/models/openconfig-extensions.yang
//  - ../api/yang/public/release/models/types/openconfig-yang-types.yang
//  - ../api/yang/public/release/models/types/openconfig-inet-types.yang
//  - ../api/yang/public/release/models/types/openconfig-types.yang
//  - ../api/yang/public/release/models/segment-routing/openconfig-srte-policy.yang
//  - ../api/yang/public/release/models/segment-routing/openconfig-rsvp-sr-ext.yang
//  - ../api/yang/public/release/models/segment-routing/openconfig-segment-routing-types.yang
//  - ../api/yang/public/release/models/segment-routing/openconfig-segment-routing.yang
//  - ../api/yang/public/release/models/mpls/openconfig-mpls-types.yang
//  - ../api/yang/public/release/models/mpls/openconfig-mpls-igp.yang
//  - ../api/yang/public/release/models/mpls/openconfig-mpls-te.yang
//  - ../api/yang/public/release/models/mpls/openconfig-mpls-rsvp.yang
//  - ../api/yang/public/release/models/mpls/openconfig-mpls-static.yang
//  - ../api/yang/public/release/models/mpls/openconfig-mpls.yang
//  - ../api/yang/public/release/models/mpls/openconfig-mpls-sr.yang
//  - ../api/yang/public/release/models/mpls/openconfig-mpls-ldp.yang
//  - ../api/yang/public/release/models/probes/openconfig-probes-types.yang
//  - ../api/yang/public/release/models/probes/openconfig-probes.yang
//  - ../api/yang/public/release/models/isis/openconfig-isis-lsp.yang
//  - ../api/yang/public/release/models/isis/openconfig-isis-lsdb-types.yang
//  - ../api/yang/public/release/models/isis/openconfig-isis-policy.yang
//  - ../api/yang/public/release/models/isis/openconfig-isis.yang
//  - ../api/yang/public/release/models/isis/openconfig-isis-types.yang
//  - ../api/yang/public/release/models/isis/openconfig-isis-routing.yang
//  - ../api/yang/public/release/models/ospf/openconfig-ospfv2-area.yang
//  - ../api/yang/public/release/models/ospf/openconfig-ospf-policy.yang
//  - ../api/yang/public/release/models/ospf/openconfig-ospfv2.yang
//  - ../api/yang/public/release/models/ospf/openconfig-ospfv2-common.yang
//  - ../api/yang/public/release/models/ospf/openconfig-ospfv2-global.yang
//  - ../api/yang/public/release/models/ospf/openconfig-ospfv2-area-interface.yang
//  - ../api/yang/public/release/models/ospf/openconfig-ospfv2-lsdb.yang
//  - ../api/yang/public/release/models/ospf/openconfig-ospf-types.yang
//  - ../api/yang/public/release/models/local-routing/openconfig-local-routing.yang
//  - ../api/yang/public/release/models/network-instance/openconfig-network-instance.yang
//  - ../api/yang/public/release/models/network-instance/openconfig-network-instance-l3.yang
//  - ../api/yang/public/release/models/network-instance/openconfig-network-instance-l2.yang
//  - ../api/yang/public/release/models/network-instance/openconfig-network-instance-policy.yang
//  - ../api/yang/public/release/models/network-instance/openconfig-network-instance-types.yang
//  - ../api/yang/public/release/models/aft/openconfig-aft-mpls.yang
//  - ../api/yang/public/release/models/aft/openconfig-aft-common.yang
//  - ../api/yang/public/release/models/aft/openconfig-aft-types.yang
//  - ../api/yang/public/release/models/aft/openconfig-aft-ipv6.yang
//  - ../api/yang/public/release/models/aft/openconfig-aft.yang
//  - ../api/yang/public/release/models/aft/openconfig-aft-pf.yang
//  - ../api/yang/public/release/models/aft/openconfig-aft-network-instance.yang
//  - ../api/yang/public/release/models/aft/openconfig-aft-ipv4.yang
//  - ../api/yang/public/release/models/aft/openconfig-aft-ethernet.yang

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: openconfig_example.proto

package openconfig

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/openconfig/ygot/proto/yext"
	ywrapper "github.com/openconfig/ygot/proto/ywrapper"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Example struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config   *Example_Config   `protobuf:"bytes,294444069,opt,name=config,proto3" json:"config,omitempty"`
	DataSetA *Example_DataSetA `protobuf:"bytes,459012710,opt,name=data_set_a,json=dataSetA,proto3" json:"data_set_a,omitempty"`
	Entries  *Example_Entries  `protobuf:"bytes,195446441,opt,name=entries,proto3" json:"entries,omitempty"`
	State    *Example_State    `protobuf:"bytes,289569434,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Example) Reset() {
	*x = Example{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openconfig_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_openconfig_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_openconfig_example_proto_rawDescGZIP(), []int{0}
}

func (x *Example) GetConfig() *Example_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Example) GetDataSetA() *Example_DataSetA {
	if x != nil {
		return x.DataSetA
	}
	return nil
}

func (x *Example) GetEntries() *Example_Entries {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Example) GetState() *Example_State {
	if x != nil {
		return x.State
	}
	return nil
}

type Example_Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable *ywrapper.BoolValue `protobuf:"bytes,490025333,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *Example_Config) Reset() {
	*x = Example_Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openconfig_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example_Config) ProtoMessage() {}

func (x *Example_Config) ProtoReflect() protoreflect.Message {
	mi := &file_openconfig_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example_Config.ProtoReflect.Descriptor instead.
func (*Example_Config) Descriptor() ([]byte, []int) {
	return file_openconfig_example_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Example_Config) GetEnable() *ywrapper.BoolValue {
	if x != nil {
		return x.Enable
	}
	return nil
}

type Example_DataSetA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Example_DataSetA_Config `protobuf:"bytes,288261735,opt,name=config,proto3" json:"config,omitempty"`
	State  *Example_DataSetA_State  `protobuf:"bytes,246179160,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Example_DataSetA) Reset() {
	*x = Example_DataSetA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openconfig_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example_DataSetA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example_DataSetA) ProtoMessage() {}

func (x *Example_DataSetA) ProtoReflect() protoreflect.Message {
	mi := &file_openconfig_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example_DataSetA.ProtoReflect.Descriptor instead.
func (*Example_DataSetA) Descriptor() ([]byte, []int) {
	return file_openconfig_example_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Example_DataSetA) GetConfig() *Example_DataSetA_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Example_DataSetA) GetState() *Example_DataSetA_State {
	if x != nil {
		return x.State
	}
	return nil
}

type Example_Entries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry []*Example_Entries_EntryKey `protobuf:"bytes,435273472,rep,name=entry,proto3" json:"entry,omitempty"`
}

func (x *Example_Entries) Reset() {
	*x = Example_Entries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openconfig_example_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example_Entries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example_Entries) ProtoMessage() {}

func (x *Example_Entries) ProtoReflect() protoreflect.Message {
	mi := &file_openconfig_example_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example_Entries.ProtoReflect.Descriptor instead.
func (*Example_Entries) Descriptor() ([]byte, []int) {
	return file_openconfig_example_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Example_Entries) GetEntry() []*Example_Entries_EntryKey {
	if x != nil {
		return x.Entry
	}
	return nil
}

type Example_State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable *ywrapper.BoolValue `protobuf:"bytes,270089844,opt,name=enable,proto3" json:"enable,omitempty"`
}

func (x *Example_State) Reset() {
	*x = Example_State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openconfig_example_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example_State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example_State) ProtoMessage() {}

func (x *Example_State) ProtoReflect() protoreflect.Message {
	mi := &file_openconfig_example_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example_State.ProtoReflect.Descriptor instead.
func (*Example_State) Descriptor() ([]byte, []int) {
	return file_openconfig_example_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Example_State) GetEnable() *ywrapper.BoolValue {
	if x != nil {
		return x.Enable
	}
	return nil
}

type Example_DataSetA_Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ItemA:
	//	*Example_DataSetA_Config_ItemAString
	//	*Example_DataSetA_Config_ItemAUint64
	ItemA  isExample_DataSetA_Config_ItemA `protobuf_oneof:"item_a"`
	Labels []*ywrapper.UintValue           `protobuf:"bytes,364545287,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *Example_DataSetA_Config) Reset() {
	*x = Example_DataSetA_Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openconfig_example_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example_DataSetA_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example_DataSetA_Config) ProtoMessage() {}

func (x *Example_DataSetA_Config) ProtoReflect() protoreflect.Message {
	mi := &file_openconfig_example_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example_DataSetA_Config.ProtoReflect.Descriptor instead.
func (*Example_DataSetA_Config) Descriptor() ([]byte, []int) {
	return file_openconfig_example_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (m *Example_DataSetA_Config) GetItemA() isExample_DataSetA_Config_ItemA {
	if m != nil {
		return m.ItemA
	}
	return nil
}

func (x *Example_DataSetA_Config) GetItemAString() string {
	if x, ok := x.GetItemA().(*Example_DataSetA_Config_ItemAString); ok {
		return x.ItemAString
	}
	return ""
}

func (x *Example_DataSetA_Config) GetItemAUint64() uint64 {
	if x, ok := x.GetItemA().(*Example_DataSetA_Config_ItemAUint64); ok {
		return x.ItemAUint64
	}
	return 0
}

func (x *Example_DataSetA_Config) GetLabels() []*ywrapper.UintValue {
	if x != nil {
		return x.Labels
	}
	return nil
}

type isExample_DataSetA_Config_ItemA interface {
	isExample_DataSetA_Config_ItemA()
}

type Example_DataSetA_Config_ItemAString struct {
	ItemAString string `protobuf:"bytes,198631831,opt,name=item_a_string,json=itemAString,proto3,oneof"`
}

type Example_DataSetA_Config_ItemAUint64 struct {
	ItemAUint64 uint64 `protobuf:"varint,48518250,opt,name=item_a_uint64,json=itemAUint64,proto3,oneof"`
}

func (*Example_DataSetA_Config_ItemAString) isExample_DataSetA_Config_ItemA() {}

func (*Example_DataSetA_Config_ItemAUint64) isExample_DataSetA_Config_ItemA() {}

type Example_DataSetA_State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CounterA *ywrapper.UintValue `protobuf:"bytes,412242891,opt,name=counter_a,json=counterA,proto3" json:"counter_a,omitempty"`
	// Types that are assignable to ItemA:
	//	*Example_DataSetA_State_ItemAString
	//	*Example_DataSetA_State_ItemAUint64
	ItemA  isExample_DataSetA_State_ItemA `protobuf_oneof:"item_a"`
	Labels []*ywrapper.UintValue          `protobuf:"bytes,65482478,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *Example_DataSetA_State) Reset() {
	*x = Example_DataSetA_State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openconfig_example_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example_DataSetA_State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example_DataSetA_State) ProtoMessage() {}

func (x *Example_DataSetA_State) ProtoReflect() protoreflect.Message {
	mi := &file_openconfig_example_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example_DataSetA_State.ProtoReflect.Descriptor instead.
func (*Example_DataSetA_State) Descriptor() ([]byte, []int) {
	return file_openconfig_example_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *Example_DataSetA_State) GetCounterA() *ywrapper.UintValue {
	if x != nil {
		return x.CounterA
	}
	return nil
}

func (m *Example_DataSetA_State) GetItemA() isExample_DataSetA_State_ItemA {
	if m != nil {
		return m.ItemA
	}
	return nil
}

func (x *Example_DataSetA_State) GetItemAString() string {
	if x, ok := x.GetItemA().(*Example_DataSetA_State_ItemAString); ok {
		return x.ItemAString
	}
	return ""
}

func (x *Example_DataSetA_State) GetItemAUint64() uint64 {
	if x, ok := x.GetItemA().(*Example_DataSetA_State_ItemAUint64); ok {
		return x.ItemAUint64
	}
	return 0
}

func (x *Example_DataSetA_State) GetLabels() []*ywrapper.UintValue {
	if x != nil {
		return x.Labels
	}
	return nil
}

type isExample_DataSetA_State_ItemA interface {
	isExample_DataSetA_State_ItemA()
}

type Example_DataSetA_State_ItemAString struct {
	ItemAString string `protobuf:"bytes,219195696,opt,name=item_a_string,json=itemAString,proto3,oneof"`
}

type Example_DataSetA_State_ItemAUint64 struct {
	ItemAUint64 uint64 `protobuf:"varint,367576745,opt,name=item_a_uint64,json=itemAUint64,proto3,oneof"`
}

func (*Example_DataSetA_State_ItemAString) isExample_DataSetA_State_ItemA() {}

func (*Example_DataSetA_State_ItemAUint64) isExample_DataSetA_State_ItemA() {}

type Example_Entries_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Example_Entries_Entry_Config `protobuf:"bytes,11350133,opt,name=config,proto3" json:"config,omitempty"`
	State  *Example_Entries_Entry_State  `protobuf:"bytes,372150122,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Example_Entries_Entry) Reset() {
	*x = Example_Entries_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openconfig_example_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example_Entries_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example_Entries_Entry) ProtoMessage() {}

func (x *Example_Entries_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_openconfig_example_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example_Entries_Entry.ProtoReflect.Descriptor instead.
func (*Example_Entries_Entry) Descriptor() ([]byte, []int) {
	return file_openconfig_example_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Example_Entries_Entry) GetConfig() *Example_Entries_Entry_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Example_Entries_Entry) GetState() *Example_Entries_Entry_State {
	if x != nil {
		return x.State
	}
	return nil
}

type Example_Entries_EntryKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Entry *Example_Entries_Entry `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *Example_Entries_EntryKey) Reset() {
	*x = Example_Entries_EntryKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openconfig_example_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example_Entries_EntryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example_Entries_EntryKey) ProtoMessage() {}

func (x *Example_Entries_EntryKey) ProtoReflect() protoreflect.Message {
	mi := &file_openconfig_example_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example_Entries_EntryKey.ProtoReflect.Descriptor instead.
func (*Example_Entries_EntryKey) Descriptor() ([]byte, []int) {
	return file_openconfig_example_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *Example_Entries_EntryKey) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Example_Entries_EntryKey) GetEntry() *Example_Entries_Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type Example_Entries_Entry_Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag  OpenconfigExampleBASEIDENTITY `protobuf:"varint,143043334,opt,name=flag,proto3,enum=openconfig.OpenconfigExampleBASEIDENTITY" json:"flag,omitempty"`
	Index *ywrapper.UintValue           `protobuf:"bytes,59002580,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *Example_Entries_Entry_Config) Reset() {
	*x = Example_Entries_Entry_Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openconfig_example_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example_Entries_Entry_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example_Entries_Entry_Config) ProtoMessage() {}

func (x *Example_Entries_Entry_Config) ProtoReflect() protoreflect.Message {
	mi := &file_openconfig_example_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example_Entries_Entry_Config.ProtoReflect.Descriptor instead.
func (*Example_Entries_Entry_Config) Descriptor() ([]byte, []int) {
	return file_openconfig_example_proto_rawDescGZIP(), []int{0, 2, 0, 0}
}

func (x *Example_Entries_Entry_Config) GetFlag() OpenconfigExampleBASEIDENTITY {
	if x != nil {
		return x.Flag
	}
	return OpenconfigExampleBASEIDENTITY_OPENCONFIGEXAMPLEBASEIDENTITY_UNSET
}

func (x *Example_Entries_Entry_Config) GetIndex() *ywrapper.UintValue {
	if x != nil {
		return x.Index
	}
	return nil
}

type Example_Entries_Entry_State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag           OpenconfigExampleBASEIDENTITY `protobuf:"varint,176766495,opt,name=flag,proto3,enum=openconfig.OpenconfigExampleBASEIDENTITY" json:"flag,omitempty"`
	Index          *ywrapper.UintValue           `protobuf:"bytes,355937315,opt,name=index,proto3" json:"index,omitempty"`
	NegotiatedFlag OpenconfigExampleBASEIDENTITY `protobuf:"varint,8765752,opt,name=negotiated_flag,json=negotiatedFlag,proto3,enum=openconfig.OpenconfigExampleBASEIDENTITY" json:"negotiated_flag,omitempty"`
}

func (x *Example_Entries_Entry_State) Reset() {
	*x = Example_Entries_Entry_State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_openconfig_example_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Example_Entries_Entry_State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example_Entries_Entry_State) ProtoMessage() {}

func (x *Example_Entries_Entry_State) ProtoReflect() protoreflect.Message {
	mi := &file_openconfig_example_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example_Entries_Entry_State.ProtoReflect.Descriptor instead.
func (*Example_Entries_Entry_State) Descriptor() ([]byte, []int) {
	return file_openconfig_example_proto_rawDescGZIP(), []int{0, 2, 0, 1}
}

func (x *Example_Entries_Entry_State) GetFlag() OpenconfigExampleBASEIDENTITY {
	if x != nil {
		return x.Flag
	}
	return OpenconfigExampleBASEIDENTITY_OPENCONFIGEXAMPLEBASEIDENTITY_UNSET
}

func (x *Example_Entries_Entry_State) GetIndex() *ywrapper.UintValue {
	if x != nil {
		return x.Index
	}
	return nil
}

func (x *Example_Entries_Entry_State) GetNegotiatedFlag() OpenconfigExampleBASEIDENTITY {
	if x != nil {
		return x.NegotiatedFlag
	}
	return OpenconfigExampleBASEIDENTITY_OPENCONFIGEXAMPLEBASEIDENTITY_UNSET
}

var File_openconfig_example_proto protoreflect.FileDescriptor

var file_openconfig_example_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6f, 0x70, 0x65, 0x6e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x0e, 0x79, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x79, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x16, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x65,
	0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe1, 0x10, 0x0a, 0x07, 0x45,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x4a, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0xa5, 0xb8, 0xb3, 0x8c, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x12, 0x82, 0x41, 0x0f, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x56, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x61,
	0x18, 0xe6, 0xf4, 0xef, 0xda, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x74, 0x41, 0x42, 0x16, 0x82, 0x41, 0x13, 0x2f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x73, 0x65, 0x74, 0x2d, 0x61,
	0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x53, 0x65, 0x74, 0x41, 0x12, 0x4d, 0x0a, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0xa9, 0x8d, 0x99, 0x5d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x45, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x13, 0x82, 0x41, 0x10,
	0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x46, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x9a, 0xf5, 0x89, 0x8a, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x11, 0x82, 0x41, 0x0e, 0x2f, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x1a, 0x54, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x4a, 0x0a, 0x06, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0xf5, 0xe2, 0xd4, 0xe9, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x79, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x19, 0x82, 0x41, 0x16, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x9d, 0x05, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x65, 0x74, 0x41, 0x12, 0x5e, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0xe7,
	0x8c, 0xba, 0x89, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x65, 0x74, 0x41, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x1d, 0x82,
	0x41, 0x1a, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2d,
	0x73, 0x65, 0x74, 0x2d, 0x61, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x59, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0xd8, 0xca,
	0xb1, 0x75, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x53, 0x65, 0x74, 0x41, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x1c, 0x82, 0x41, 0x19, 0x2f,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x73, 0x65, 0x74,
	0x2d, 0x61, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x1a,
	0xbb, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x27, 0x0a, 0x0d, 0x69, 0x74,
	0x65, 0x6d, 0x5f, 0x61, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x97, 0xc3, 0xdb, 0x5e,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x74, 0x65, 0x6d, 0x41, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x27, 0x0a, 0x0d, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x61, 0x5f, 0x75, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x18, 0xea, 0xa8, 0x91, 0x17, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52,
	0x0b, 0x69, 0x74, 0x65, 0x6d, 0x41, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x55, 0x0a, 0x06,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x87, 0x8a, 0xea, 0xad, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x79, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x55, 0x69, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x24, 0x82, 0x41, 0x21, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x73, 0x65, 0x74, 0x2d, 0x61, 0x2f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x06, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x61, 0x1a, 0x97, 0x02,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x5c, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x5f, 0x61, 0x18, 0xcb, 0xa7, 0xc9, 0xc4, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x79, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x26, 0x82, 0x41, 0x23, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x73, 0x65, 0x74, 0x2d, 0x61, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2d, 0x61, 0x52, 0x08, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x41, 0x12, 0x27, 0x0a, 0x0d, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x61, 0x5f,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0xb0, 0xd2, 0xc2, 0x68, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0b, 0x69, 0x74, 0x65, 0x6d, 0x41, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x28,
	0x0a, 0x0d, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x61, 0x5f, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18,
	0xa9, 0x8d, 0xa3, 0xaf, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x74, 0x65,
	0x6d, 0x41, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x53, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x18, 0xee, 0xdd, 0x9c, 0x1f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x79, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x42, 0x23, 0x82, 0x41, 0x20, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x2d, 0x73, 0x65, 0x74, 0x2d, 0x61, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x73, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x42, 0x08, 0x0a,
	0x06, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x61, 0x1a, 0xd0, 0x07, 0x0a, 0x07, 0x45, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x59, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x80, 0xfe, 0xc6,
	0xcf, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x42, 0x19, 0x82, 0x41,
	0x16, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0xed,
	0x05, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x65, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x18, 0xf5, 0xe0, 0xb4, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x20, 0x82, 0x41, 0x1d, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x62, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0xea, 0x9e, 0xba, 0xb1, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x1f, 0x82, 0x41, 0x1c,
	0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x2f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x1a, 0xc7, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x67,
	0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x86, 0xd6, 0x9a, 0x44, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x29, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4f, 0x70, 0x65,
	0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x42, 0x41,
	0x53, 0x45, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x42, 0x25, 0x82, 0x41, 0x22, 0x2f,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2f,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x66, 0x6c, 0x61,
	0x67, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x54, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0xd4, 0x9d, 0x91, 0x1c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x79, 0x77, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x26,
	0x82, 0x41, 0x23, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0xce, 0x02,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x66, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18,
	0x9f, 0xfc, 0xa4, 0x54, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x42, 0x41, 0x53, 0x45, 0x49, 0x44, 0x45, 0x4e, 0x54,
	0x49, 0x54, 0x59, 0x42, 0x24, 0x82, 0x41, 0x21, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x2f, 0x66, 0x6c, 0x61, 0x67, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12,
	0x54, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0xa3, 0xd8, 0xdc, 0xa9, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x79, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x55, 0x69,
	0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x25, 0x82, 0x41, 0x22, 0x2f, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x86, 0x01, 0x0a, 0x0f, 0x6e, 0x65, 0x67, 0x6f, 0x74, 0x69,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0xb8, 0x82, 0x97, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x4f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x42, 0x41, 0x53, 0x45, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x42, 0x2f, 0x82,
	0x41, 0x2c, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x6e,
	0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x65, 0x64, 0x2d, 0x66, 0x6c, 0x61, 0x67, 0x52, 0x0e,
	0x6e, 0x65, 0x67, 0x6f, 0x74, 0x69, 0x61, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x1a, 0x7a,
	0x0a, 0x08, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x35, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x1f, 0x82, 0x41, 0x1c, 0x2f, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2f, 0x65,
	0x6e, 0x74, 0x72, 0x79, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x37, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x45, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x1a, 0x52, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x49, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0xf4, 0xfc,
	0xe4, 0x80, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x79, 0x77, 0x72, 0x61, 0x70, 0x70,
	0x65, 0x72, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x18, 0x82, 0x41,
	0x15, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x17,
	0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x6e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_openconfig_example_proto_rawDescOnce sync.Once
	file_openconfig_example_proto_rawDescData = file_openconfig_example_proto_rawDesc
)

func file_openconfig_example_proto_rawDescGZIP() []byte {
	file_openconfig_example_proto_rawDescOnce.Do(func() {
		file_openconfig_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_openconfig_example_proto_rawDescData)
	})
	return file_openconfig_example_proto_rawDescData
}

var file_openconfig_example_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_openconfig_example_proto_goTypes = []interface{}{
	(*Example)(nil),                      // 0: openconfig.Example
	(*Example_Config)(nil),               // 1: openconfig.Example.Config
	(*Example_DataSetA)(nil),             // 2: openconfig.Example.DataSetA
	(*Example_Entries)(nil),              // 3: openconfig.Example.Entries
	(*Example_State)(nil),                // 4: openconfig.Example.State
	(*Example_DataSetA_Config)(nil),      // 5: openconfig.Example.DataSetA.Config
	(*Example_DataSetA_State)(nil),       // 6: openconfig.Example.DataSetA.State
	(*Example_Entries_Entry)(nil),        // 7: openconfig.Example.Entries.Entry
	(*Example_Entries_EntryKey)(nil),     // 8: openconfig.Example.Entries.EntryKey
	(*Example_Entries_Entry_Config)(nil), // 9: openconfig.Example.Entries.Entry.Config
	(*Example_Entries_Entry_State)(nil),  // 10: openconfig.Example.Entries.Entry.State
	(*ywrapper.BoolValue)(nil),           // 11: ywrapper.BoolValue
	(*ywrapper.UintValue)(nil),           // 12: ywrapper.UintValue
	(OpenconfigExampleBASEIDENTITY)(0),   // 13: openconfig.OpenconfigExampleBASEIDENTITY
}
var file_openconfig_example_proto_depIdxs = []int32{
	1,  // 0: openconfig.Example.config:type_name -> openconfig.Example.Config
	2,  // 1: openconfig.Example.data_set_a:type_name -> openconfig.Example.DataSetA
	3,  // 2: openconfig.Example.entries:type_name -> openconfig.Example.Entries
	4,  // 3: openconfig.Example.state:type_name -> openconfig.Example.State
	11, // 4: openconfig.Example.Config.enable:type_name -> ywrapper.BoolValue
	5,  // 5: openconfig.Example.DataSetA.config:type_name -> openconfig.Example.DataSetA.Config
	6,  // 6: openconfig.Example.DataSetA.state:type_name -> openconfig.Example.DataSetA.State
	8,  // 7: openconfig.Example.Entries.entry:type_name -> openconfig.Example.Entries.EntryKey
	11, // 8: openconfig.Example.State.enable:type_name -> ywrapper.BoolValue
	12, // 9: openconfig.Example.DataSetA.Config.labels:type_name -> ywrapper.UintValue
	12, // 10: openconfig.Example.DataSetA.State.counter_a:type_name -> ywrapper.UintValue
	12, // 11: openconfig.Example.DataSetA.State.labels:type_name -> ywrapper.UintValue
	9,  // 12: openconfig.Example.Entries.Entry.config:type_name -> openconfig.Example.Entries.Entry.Config
	10, // 13: openconfig.Example.Entries.Entry.state:type_name -> openconfig.Example.Entries.Entry.State
	7,  // 14: openconfig.Example.Entries.EntryKey.entry:type_name -> openconfig.Example.Entries.Entry
	13, // 15: openconfig.Example.Entries.Entry.Config.flag:type_name -> openconfig.OpenconfigExampleBASEIDENTITY
	12, // 16: openconfig.Example.Entries.Entry.Config.index:type_name -> ywrapper.UintValue
	13, // 17: openconfig.Example.Entries.Entry.State.flag:type_name -> openconfig.OpenconfigExampleBASEIDENTITY
	12, // 18: openconfig.Example.Entries.Entry.State.index:type_name -> ywrapper.UintValue
	13, // 19: openconfig.Example.Entries.Entry.State.negotiated_flag:type_name -> openconfig.OpenconfigExampleBASEIDENTITY
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_openconfig_example_proto_init() }
func file_openconfig_example_proto_init() {
	if File_openconfig_example_proto != nil {
		return
	}
	file_openconfig_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_openconfig_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openconfig_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example_Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openconfig_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example_DataSetA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openconfig_example_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example_Entries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openconfig_example_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example_State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openconfig_example_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example_DataSetA_Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openconfig_example_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example_DataSetA_State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openconfig_example_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example_Entries_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openconfig_example_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example_Entries_EntryKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openconfig_example_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example_Entries_Entry_Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_openconfig_example_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Example_Entries_Entry_State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_openconfig_example_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Example_DataSetA_Config_ItemAString)(nil),
		(*Example_DataSetA_Config_ItemAUint64)(nil),
	}
	file_openconfig_example_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*Example_DataSetA_State_ItemAString)(nil),
		(*Example_DataSetA_State_ItemAUint64)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_openconfig_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openconfig_example_proto_goTypes,
		DependencyIndexes: file_openconfig_example_proto_depIdxs,
		MessageInfos:      file_openconfig_example_proto_msgTypes,
	}.Build()
	File_openconfig_example_proto = out.File
	file_openconfig_example_proto_rawDesc = nil
	file_openconfig_example_proto_goTypes = nil
	file_openconfig_example_proto_depIdxs = nil
}
