// openconfig.accton_route is generated by proto_generator as a protobuf
// representation of a YANG schema.
//
// Input schema modules:
//  - ../api/yang/sonic/nocsys-types.yang
//  - ../api/yang/sonic/nocsys-interface.yang
//  - ../api/yang/sonic/nocsys-vlan.yang
//  - ../api/yang/sonic/nocsys-mdns.yang
//  - ../api/yang/sonic/nocsys-extension.yang
//  - ../api/yang/sonic/nocsys-acl.yang
//  - ../api/yang/sonic/nocsys-loopback-interface.yang
//  - ../api/yang/sonic/nocsys-vrf.yang
//  - ../api/yang/sonic/nocsys-portchannel.yang
//  - ../api/yang/sonic/nocsys-system.yang
//  - ../api/yang/sonic/nocsys-neighbor.yang
//  - ../api/yang/sonic/nocsys-vxlan.yang
//  - ../api/yang/sonic/nocsys-port.yang
//  - ../api/yang/sonic/nocsys-route.yang
//  - ../api/yang/sonic/nocsys-ntp.yang
//  - ../api/yang/sonic/nocsys-fdb.yang
//  - ../api/yang/sonic/nocsys-platform-types.yang
//  - ../api/yang/sonic/nocsys-platform.yang
//  - ../api/yang/sonic/nocsys-lldp.yang
//  - ../api/yang/sonic/nocsys-mirror-session.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-inet-types.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-yang-types.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-interfaces.yang
//  - ../api/yang/sonic/third_party/ietf/iana-if-type.yang
//  - ../api/yang/sonic/third_party/openconfig/openconfig-types.yang
//  - ../api/yang/sonic/third_party/openconfig/openconfig-extensions.yang
//  - ../api/yang/sonic/nocsys-todo.yang

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: accton_route.proto

package sonic

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/openconfig/ygot/proto/yext"
	ywrapper "github.com/openconfig/ygot/proto/ywrapper"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AcctonRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Route *AcctonRoute_Route `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
}

func (x *AcctonRoute) Reset() {
	*x = AcctonRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accton_route_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcctonRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcctonRoute) ProtoMessage() {}

func (x *AcctonRoute) ProtoReflect() protoreflect.Message {
	mi := &file_accton_route_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcctonRoute.ProtoReflect.Descriptor instead.
func (*AcctonRoute) Descriptor() ([]byte, []int) {
	return file_accton_route_proto_rawDescGZIP(), []int{0}
}

func (x *AcctonRoute) GetRoute() *AcctonRoute_Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type AcctonRoute_Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteList []*AcctonRoute_Route_RouteListKey `protobuf:"bytes,1,rep,name=route_list,json=routeList,proto3" json:"route_list,omitempty"`
}

func (x *AcctonRoute_Route) Reset() {
	*x = AcctonRoute_Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accton_route_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcctonRoute_Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcctonRoute_Route) ProtoMessage() {}

func (x *AcctonRoute_Route) ProtoReflect() protoreflect.Message {
	mi := &file_accton_route_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcctonRoute_Route.ProtoReflect.Descriptor instead.
func (*AcctonRoute_Route) Descriptor() ([]byte, []int) {
	return file_accton_route_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AcctonRoute_Route) GetRouteList() []*AcctonRoute_Route_RouteListKey {
	if x != nil {
		return x.RouteList
	}
	return nil
}

type AcctonRoute_Route_RouteList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ifname  *ywrapper.StringValue `protobuf:"bytes,1,opt,name=ifname,proto3" json:"ifname,omitempty"`
	Nexthop *ywrapper.StringValue `protobuf:"bytes,2,opt,name=nexthop,proto3" json:"nexthop,omitempty"`
}

func (x *AcctonRoute_Route_RouteList) Reset() {
	*x = AcctonRoute_Route_RouteList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accton_route_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcctonRoute_Route_RouteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcctonRoute_Route_RouteList) ProtoMessage() {}

func (x *AcctonRoute_Route_RouteList) ProtoReflect() protoreflect.Message {
	mi := &file_accton_route_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcctonRoute_Route_RouteList.ProtoReflect.Descriptor instead.
func (*AcctonRoute_Route_RouteList) Descriptor() ([]byte, []int) {
	return file_accton_route_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *AcctonRoute_Route_RouteList) GetIfname() *ywrapper.StringValue {
	if x != nil {
		return x.Ifname
	}
	return nil
}

func (x *AcctonRoute_Route_RouteList) GetNexthop() *ywrapper.StringValue {
	if x != nil {
		return x.Nexthop
	}
	return nil
}

type AcctonRoute_Route_RouteListKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VrfName   string                       `protobuf:"bytes,1,opt,name=vrf_name,json=vrfName,proto3" json:"vrf_name,omitempty"`
	IpPrefix  string                       `protobuf:"bytes,2,opt,name=ip_prefix,json=ipPrefix,proto3" json:"ip_prefix,omitempty"`
	RouteList *AcctonRoute_Route_RouteList `protobuf:"bytes,3,opt,name=route_list,json=routeList,proto3" json:"route_list,omitempty"`
}

func (x *AcctonRoute_Route_RouteListKey) Reset() {
	*x = AcctonRoute_Route_RouteListKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accton_route_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcctonRoute_Route_RouteListKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcctonRoute_Route_RouteListKey) ProtoMessage() {}

func (x *AcctonRoute_Route_RouteListKey) ProtoReflect() protoreflect.Message {
	mi := &file_accton_route_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcctonRoute_Route_RouteListKey.ProtoReflect.Descriptor instead.
func (*AcctonRoute_Route_RouteListKey) Descriptor() ([]byte, []int) {
	return file_accton_route_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *AcctonRoute_Route_RouteListKey) GetVrfName() string {
	if x != nil {
		return x.VrfName
	}
	return ""
}

func (x *AcctonRoute_Route_RouteListKey) GetIpPrefix() string {
	if x != nil {
		return x.IpPrefix
	}
	return ""
}

func (x *AcctonRoute_Route_RouteListKey) GetRouteList() *AcctonRoute_Route_RouteList {
	if x != nil {
		return x.RouteList
	}
	return nil
}

var File_accton_route_proto protoreflect.FileDescriptor

var file_accton_route_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x63, 0x63, 0x74, 0x6f, 0x6e, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x1a, 0x0e, 0x79, 0x77, 0x72,
	0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x79, 0x65, 0x78,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf0, 0x04, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x74,
	0x6f, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x46, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x41,
	0x63, 0x63, 0x74, 0x6f, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x42, 0x16, 0x82, 0x41, 0x13, 0x2f, 0x61, 0x63, 0x63, 0x74, 0x6f, 0x6e, 0x2d, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x1a,
	0x98, 0x04, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x67, 0x0a, 0x0a, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x41, 0x63, 0x63, 0x74, 0x6f, 0x6e, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x4b, 0x65, 0x79, 0x42, 0x21, 0x82, 0x41, 0x1e, 0x2f, 0x61, 0x63, 0x63, 0x74, 0x6f, 0x6e,
	0x2d, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x1a, 0xc0, 0x01, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x57, 0x0a, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x79, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x28, 0x82, 0x41, 0x25, 0x2f, 0x61, 0x63, 0x63,
	0x74, 0x6f, 0x6e, 0x2d, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x69, 0x66, 0x6e, 0x61, 0x6d,
	0x65, 0x52, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x5a, 0x0a, 0x07, 0x6e, 0x65, 0x78,
	0x74, 0x68, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x79, 0x77, 0x72,
	0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x29, 0x82, 0x41, 0x26, 0x2f, 0x61, 0x63, 0x63, 0x74, 0x6f, 0x6e, 0x2d, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2d,
	0x6c, 0x69, 0x73, 0x74, 0x2f, 0x6e, 0x65, 0x78, 0x74, 0x68, 0x6f, 0x70, 0x52, 0x07, 0x6e, 0x65,
	0x78, 0x74, 0x68, 0x6f, 0x70, 0x1a, 0xe2, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x45, 0x0a, 0x08, 0x76, 0x72, 0x66, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x2a, 0x82, 0x41, 0x27, 0x2f, 0x61, 0x63,
	0x63, 0x74, 0x6f, 0x6e, 0x2d, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x76, 0x72, 0x66, 0x2d,
	0x6e, 0x61, 0x6d, 0x65, 0x52, 0x07, 0x76, 0x72, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x48, 0x0a,
	0x09, 0x69, 0x70, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x2b, 0x82, 0x41, 0x28, 0x2f, 0x61, 0x63, 0x63, 0x74, 0x6f, 0x6e, 0x2d, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2d, 0x6c,
	0x69, 0x73, 0x74, 0x2f, 0x69, 0x70, 0x2d, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x08, 0x69,
	0x70, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x41, 0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x6f,
	0x6e, 0x69, 0x63, 0x2e, 0x41, 0x63, 0x63, 0x74, 0x6f, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x2e,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x09, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x1b, 0x0a, 0x10, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x63, 0x63, 0x74, 0x6f, 0x6e, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x5a, 0x07,
	0x2e, 0x3b, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accton_route_proto_rawDescOnce sync.Once
	file_accton_route_proto_rawDescData = file_accton_route_proto_rawDesc
)

func file_accton_route_proto_rawDescGZIP() []byte {
	file_accton_route_proto_rawDescOnce.Do(func() {
		file_accton_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_accton_route_proto_rawDescData)
	})
	return file_accton_route_proto_rawDescData
}

var file_accton_route_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_accton_route_proto_goTypes = []interface{}{
	(*AcctonRoute)(nil),                    // 0: sonic.AcctonRoute
	(*AcctonRoute_Route)(nil),              // 1: sonic.AcctonRoute.Route
	(*AcctonRoute_Route_RouteList)(nil),    // 2: sonic.AcctonRoute.Route.RouteList
	(*AcctonRoute_Route_RouteListKey)(nil), // 3: sonic.AcctonRoute.Route.RouteListKey
	(*ywrapper.StringValue)(nil),           // 4: ywrapper.StringValue
}
var file_accton_route_proto_depIdxs = []int32{
	1, // 0: sonic.AcctonRoute.route:type_name -> sonic.AcctonRoute.Route
	3, // 1: sonic.AcctonRoute.Route.route_list:type_name -> sonic.AcctonRoute.Route.RouteListKey
	4, // 2: sonic.AcctonRoute.Route.RouteList.ifname:type_name -> ywrapper.StringValue
	4, // 3: sonic.AcctonRoute.Route.RouteList.nexthop:type_name -> ywrapper.StringValue
	2, // 4: sonic.AcctonRoute.Route.RouteListKey.route_list:type_name -> sonic.AcctonRoute.Route.RouteList
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_accton_route_proto_init() }
func file_accton_route_proto_init() {
	if File_accton_route_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accton_route_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcctonRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accton_route_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcctonRoute_Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accton_route_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcctonRoute_Route_RouteList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accton_route_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcctonRoute_Route_RouteListKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accton_route_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accton_route_proto_goTypes,
		DependencyIndexes: file_accton_route_proto_depIdxs,
		MessageInfos:      file_accton_route_proto_msgTypes,
	}.Build()
	File_accton_route_proto = out.File
	file_accton_route_proto_rawDesc = nil
	file_accton_route_proto_goTypes = nil
	file_accton_route_proto_depIdxs = nil
}
