// openconfig.nocsys_neighor is generated by proto_generator as a protobuf
// representation of a YANG schema.
//
// Input schema modules:
//  - ../api/yang/sonic/nocsys-fdb.yang
//  - ../api/yang/sonic/nocsys-ntp.yang
//  - ../api/yang/sonic/nocsys-todo.yang
//  - ../api/yang/sonic/nocsys-types.yang
//  - ../api/yang/sonic/nocsys-route.yang
//  - ../api/yang/sonic/nocsys-extension.yang
//  - ../api/yang/sonic/nocsys-loopback-interface.yang
//  - ../api/yang/sonic/nocsys-portchannel.yang
//  - ../api/yang/sonic/nocsys-vlan.yang
//  - ../api/yang/sonic/nocsys-port.yang
//  - ../api/yang/sonic/nocsys-platform-types.yang
//  - ../api/yang/sonic/nocsys-mirror-session.yang
//  - ../api/yang/sonic/nocsys-vrf.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-yang-types.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-inet-types.yang
//  - ../api/yang/sonic/third_party/ietf/iana-if-type.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-interfaces.yang
//  - ../api/yang/sonic/nocsys-neighbor.yang
//  - ../api/yang/sonic/nocsys-acl.yang
//  - ../api/yang/sonic/nocsys-vxlan.yang
//  - ../api/yang/sonic/nocsys-platform.yang
//  - ../api/yang/sonic/nocsys-interface.yang
//  - ../api/yang/sonic/nocsys-lldp.yang

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: nocsys_neighor.proto

package sonic

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/openconfig/ygot/proto/yext"
	ywrapper "github.com/openconfig/ygot/proto/ywrapper"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NocsysNeighor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Neighor *NocsysNeighor_Neighor `protobuf:"bytes,1,opt,name=neighor,proto3" json:"neighor,omitempty"`
}

func (x *NocsysNeighor) Reset() {
	*x = NocsysNeighor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nocsys_neighor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NocsysNeighor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NocsysNeighor) ProtoMessage() {}

func (x *NocsysNeighor) ProtoReflect() protoreflect.Message {
	mi := &file_nocsys_neighor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NocsysNeighor.ProtoReflect.Descriptor instead.
func (*NocsysNeighor) Descriptor() ([]byte, []int) {
	return file_nocsys_neighor_proto_rawDescGZIP(), []int{0}
}

func (x *NocsysNeighor) GetNeighor() *NocsysNeighor_Neighor {
	if x != nil {
		return x.Neighor
	}
	return nil
}

type NocsysNeighor_Neighor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NeighorList []*NocsysNeighor_Neighor_NeighorListKey `protobuf:"bytes,1,rep,name=neighor_list,json=neighorList,proto3" json:"neighor_list,omitempty"`
}

func (x *NocsysNeighor_Neighor) Reset() {
	*x = NocsysNeighor_Neighor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nocsys_neighor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NocsysNeighor_Neighor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NocsysNeighor_Neighor) ProtoMessage() {}

func (x *NocsysNeighor_Neighor) ProtoReflect() protoreflect.Message {
	mi := &file_nocsys_neighor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NocsysNeighor_Neighor.ProtoReflect.Descriptor instead.
func (*NocsysNeighor_Neighor) Descriptor() ([]byte, []int) {
	return file_nocsys_neighor_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NocsysNeighor_Neighor) GetNeighorList() []*NocsysNeighor_Neighor_NeighorListKey {
	if x != nil {
		return x.NeighorList
	}
	return nil
}

type NocsysNeighor_Neighor_NeighorList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Neigh *ywrapper.StringValue `protobuf:"bytes,1,opt,name=neigh,proto3" json:"neigh,omitempty"`
}

func (x *NocsysNeighor_Neighor_NeighorList) Reset() {
	*x = NocsysNeighor_Neighor_NeighorList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nocsys_neighor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NocsysNeighor_Neighor_NeighorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NocsysNeighor_Neighor_NeighorList) ProtoMessage() {}

func (x *NocsysNeighor_Neighor_NeighorList) ProtoReflect() protoreflect.Message {
	mi := &file_nocsys_neighor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NocsysNeighor_Neighor_NeighorList.ProtoReflect.Descriptor instead.
func (*NocsysNeighor_Neighor_NeighorList) Descriptor() ([]byte, []int) {
	return file_nocsys_neighor_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *NocsysNeighor_Neighor_NeighorList) GetNeigh() *ywrapper.StringValue {
	if x != nil {
		return x.Neigh
	}
	return nil
}

type NocsysNeighor_Neighor_NeighorListKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IpPrefix    string                             `protobuf:"bytes,2,opt,name=ip_prefix,json=ipPrefix,proto3" json:"ip_prefix,omitempty"`
	NeighorList *NocsysNeighor_Neighor_NeighorList `protobuf:"bytes,3,opt,name=neighor_list,json=neighorList,proto3" json:"neighor_list,omitempty"`
}

func (x *NocsysNeighor_Neighor_NeighorListKey) Reset() {
	*x = NocsysNeighor_Neighor_NeighorListKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nocsys_neighor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NocsysNeighor_Neighor_NeighorListKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NocsysNeighor_Neighor_NeighorListKey) ProtoMessage() {}

func (x *NocsysNeighor_Neighor_NeighorListKey) ProtoReflect() protoreflect.Message {
	mi := &file_nocsys_neighor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NocsysNeighor_Neighor_NeighorListKey.ProtoReflect.Descriptor instead.
func (*NocsysNeighor_Neighor_NeighorListKey) Descriptor() ([]byte, []int) {
	return file_nocsys_neighor_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *NocsysNeighor_Neighor_NeighorListKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NocsysNeighor_Neighor_NeighorListKey) GetIpPrefix() string {
	if x != nil {
		return x.IpPrefix
	}
	return ""
}

func (x *NocsysNeighor_Neighor_NeighorListKey) GetNeighorList() *NocsysNeighor_Neighor_NeighorList {
	if x != nil {
		return x.NeighorList
	}
	return nil
}

var File_nocsys_neighor_proto protoreflect.FileDescriptor

var file_nocsys_neighor_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x5f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x1a, 0x0e, 0x79,
	0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x79,
	0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x04, 0x0a, 0x0d, 0x4e, 0x6f,
	0x63, 0x73, 0x79, 0x73, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x12, 0x52, 0x0a, 0x07, 0x6e,
	0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73,
	0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x4e, 0x65, 0x69, 0x67, 0x68,
	0x6f, 0x72, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x42, 0x1a, 0x82, 0x41, 0x17, 0x2f,
	0x6e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x2d, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e,
	0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x52, 0x07, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x1a,
	0xdf, 0x03, 0x0a, 0x07, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x12, 0x77, 0x0a, 0x0c, 0x6e,
	0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2b, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x63, 0x73, 0x79, 0x73,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2e,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x42, 0x27,
	0x82, 0x41, 0x24, 0x2f, 0x6e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x2d, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x6f, 0x72, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x0b, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x1a, 0x69, 0x0a, 0x0b, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x5a, 0x0a, 0x05, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x79, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x2d, 0x82, 0x41, 0x2a, 0x2f, 0x6e,
	0x6f, 0x63, 0x73, 0x79, 0x73, 0x2d, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65,
	0x69, 0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2d, 0x6c, 0x69,
	0x73, 0x74, 0x2f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x52, 0x05, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x1a,
	0xef, 0x01, 0x0a, 0x0e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x4b,
	0x65, 0x79, 0x12, 0x40, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x2c, 0x82, 0x41, 0x29, 0x2f, 0x6e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x2d, 0x6e, 0x65, 0x69,
	0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69,
	0x67, 0x68, 0x6f, 0x72, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4e, 0x0a, 0x09, 0x69, 0x70, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x31, 0x82, 0x41, 0x2e, 0x2f, 0x6e, 0x6f, 0x63,
	0x73, 0x79, 0x73, 0x2d, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69, 0x67,
	0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2d, 0x6c, 0x69, 0x73, 0x74,
	0x2f, 0x69, 0x70, 0x2d, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x08, 0x69, 0x70, 0x50, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x12, 0x4b, 0x0a, 0x0c, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x73, 0x6f, 0x6e,
	0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72,
	0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x0b, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x1b, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x6e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x2e,
	0x73, 0x6f, 0x6e, 0x69, 0x63, 0x5a, 0x07, 0x2e, 0x3b, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nocsys_neighor_proto_rawDescOnce sync.Once
	file_nocsys_neighor_proto_rawDescData = file_nocsys_neighor_proto_rawDesc
)

func file_nocsys_neighor_proto_rawDescGZIP() []byte {
	file_nocsys_neighor_proto_rawDescOnce.Do(func() {
		file_nocsys_neighor_proto_rawDescData = protoimpl.X.CompressGZIP(file_nocsys_neighor_proto_rawDescData)
	})
	return file_nocsys_neighor_proto_rawDescData
}

var file_nocsys_neighor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nocsys_neighor_proto_goTypes = []interface{}{
	(*NocsysNeighor)(nil),                        // 0: sonic.NocsysNeighor
	(*NocsysNeighor_Neighor)(nil),                // 1: sonic.NocsysNeighor.Neighor
	(*NocsysNeighor_Neighor_NeighorList)(nil),    // 2: sonic.NocsysNeighor.Neighor.NeighorList
	(*NocsysNeighor_Neighor_NeighorListKey)(nil), // 3: sonic.NocsysNeighor.Neighor.NeighorListKey
	(*ywrapper.StringValue)(nil),                 // 4: ywrapper.StringValue
}
var file_nocsys_neighor_proto_depIdxs = []int32{
	1, // 0: sonic.NocsysNeighor.neighor:type_name -> sonic.NocsysNeighor.Neighor
	3, // 1: sonic.NocsysNeighor.Neighor.neighor_list:type_name -> sonic.NocsysNeighor.Neighor.NeighorListKey
	4, // 2: sonic.NocsysNeighor.Neighor.NeighorList.neigh:type_name -> ywrapper.StringValue
	2, // 3: sonic.NocsysNeighor.Neighor.NeighorListKey.neighor_list:type_name -> sonic.NocsysNeighor.Neighor.NeighorList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nocsys_neighor_proto_init() }
func file_nocsys_neighor_proto_init() {
	if File_nocsys_neighor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nocsys_neighor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NocsysNeighor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nocsys_neighor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NocsysNeighor_Neighor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nocsys_neighor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NocsysNeighor_Neighor_NeighorList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nocsys_neighor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NocsysNeighor_Neighor_NeighorListKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nocsys_neighor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nocsys_neighor_proto_goTypes,
		DependencyIndexes: file_nocsys_neighor_proto_depIdxs,
		MessageInfos:      file_nocsys_neighor_proto_msgTypes,
	}.Build()
	File_nocsys_neighor_proto = out.File
	file_nocsys_neighor_proto_rawDesc = nil
	file_nocsys_neighor_proto_goTypes = nil
	file_nocsys_neighor_proto_depIdxs = nil
}
