// openconfig.nocsys_vrf is generated by proto_generator as a protobuf
// representation of a YANG schema.
//
// Input schema modules:
//  - ../api/yang/sonic/nocsys-fdb.yang
//  - ../api/yang/sonic/nocsys-ntp.yang
//  - ../api/yang/sonic/nocsys-todo.yang
//  - ../api/yang/sonic/nocsys-types.yang
//  - ../api/yang/sonic/nocsys-route.yang
//  - ../api/yang/sonic/nocsys-extension.yang
//  - ../api/yang/sonic/nocsys-loopback-interface.yang
//  - ../api/yang/sonic/nocsys-portchannel.yang
//  - ../api/yang/sonic/nocsys-vlan.yang
//  - ../api/yang/sonic/nocsys-port.yang
//  - ../api/yang/sonic/nocsys-platform-types.yang
//  - ../api/yang/sonic/nocsys-mirror-session.yang
//  - ../api/yang/sonic/nocsys-vrf.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-yang-types.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-inet-types.yang
//  - ../api/yang/sonic/third_party/ietf/iana-if-type.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-interfaces.yang
//  - ../api/yang/sonic/nocsys-neighbor.yang
//  - ../api/yang/sonic/nocsys-acl.yang
//  - ../api/yang/sonic/nocsys-vxlan.yang
//  - ../api/yang/sonic/nocsys-platform.yang
//  - ../api/yang/sonic/nocsys-interface.yang
//  - ../api/yang/sonic/nocsys-lldp.yang

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: nocsys_vrf.proto

package sonic

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/openconfig/ygot/proto/yext"
	ywrapper "github.com/openconfig/ygot/proto/ywrapper"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NocsysVrf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vrf *NocsysVrf_Vrf `protobuf:"bytes,1,opt,name=vrf,proto3" json:"vrf,omitempty"`
}

func (x *NocsysVrf) Reset() {
	*x = NocsysVrf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nocsys_vrf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NocsysVrf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NocsysVrf) ProtoMessage() {}

func (x *NocsysVrf) ProtoReflect() protoreflect.Message {
	mi := &file_nocsys_vrf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NocsysVrf.ProtoReflect.Descriptor instead.
func (*NocsysVrf) Descriptor() ([]byte, []int) {
	return file_nocsys_vrf_proto_rawDescGZIP(), []int{0}
}

func (x *NocsysVrf) GetVrf() *NocsysVrf_Vrf {
	if x != nil {
		return x.Vrf
	}
	return nil
}

type NocsysVrf_Vrf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VrfList []*NocsysVrf_Vrf_VrfListKey `protobuf:"bytes,1,rep,name=vrf_list,json=vrfList,proto3" json:"vrf_list,omitempty"`
}

func (x *NocsysVrf_Vrf) Reset() {
	*x = NocsysVrf_Vrf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nocsys_vrf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NocsysVrf_Vrf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NocsysVrf_Vrf) ProtoMessage() {}

func (x *NocsysVrf_Vrf) ProtoReflect() protoreflect.Message {
	mi := &file_nocsys_vrf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NocsysVrf_Vrf.ProtoReflect.Descriptor instead.
func (*NocsysVrf_Vrf) Descriptor() ([]byte, []int) {
	return file_nocsys_vrf_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NocsysVrf_Vrf) GetVrfList() []*NocsysVrf_Vrf_VrfListKey {
	if x != nil {
		return x.VrfList
	}
	return nil
}

type NocsysVrf_Vrf_VrfList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fallback *ywrapper.BoolValue `protobuf:"bytes,1,opt,name=fallback,proto3" json:"fallback,omitempty"`
}

func (x *NocsysVrf_Vrf_VrfList) Reset() {
	*x = NocsysVrf_Vrf_VrfList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nocsys_vrf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NocsysVrf_Vrf_VrfList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NocsysVrf_Vrf_VrfList) ProtoMessage() {}

func (x *NocsysVrf_Vrf_VrfList) ProtoReflect() protoreflect.Message {
	mi := &file_nocsys_vrf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NocsysVrf_Vrf_VrfList.ProtoReflect.Descriptor instead.
func (*NocsysVrf_Vrf_VrfList) Descriptor() ([]byte, []int) {
	return file_nocsys_vrf_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *NocsysVrf_Vrf_VrfList) GetFallback() *ywrapper.BoolValue {
	if x != nil {
		return x.Fallback
	}
	return nil
}

type NocsysVrf_Vrf_VrfListKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VrfName string                 `protobuf:"bytes,1,opt,name=vrf_name,json=vrfName,proto3" json:"vrf_name,omitempty"`
	VrfList *NocsysVrf_Vrf_VrfList `protobuf:"bytes,2,opt,name=vrf_list,json=vrfList,proto3" json:"vrf_list,omitempty"`
}

func (x *NocsysVrf_Vrf_VrfListKey) Reset() {
	*x = NocsysVrf_Vrf_VrfListKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nocsys_vrf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NocsysVrf_Vrf_VrfListKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NocsysVrf_Vrf_VrfListKey) ProtoMessage() {}

func (x *NocsysVrf_Vrf_VrfListKey) ProtoReflect() protoreflect.Message {
	mi := &file_nocsys_vrf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NocsysVrf_Vrf_VrfListKey.ProtoReflect.Descriptor instead.
func (*NocsysVrf_Vrf_VrfListKey) Descriptor() ([]byte, []int) {
	return file_nocsys_vrf_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *NocsysVrf_Vrf_VrfListKey) GetVrfName() string {
	if x != nil {
		return x.VrfName
	}
	return ""
}

func (x *NocsysVrf_Vrf_VrfListKey) GetVrfList() *NocsysVrf_Vrf_VrfList {
	if x != nil {
		return x.VrfList
	}
	return nil
}

var File_nocsys_vrf_proto protoreflect.FileDescriptor

var file_nocsys_vrf_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x5f, 0x76, 0x72, 0x66, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x1a, 0x0e, 0x79, 0x77, 0x72, 0x61, 0x70,
	0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x79, 0x65, 0x78, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x03, 0x0a, 0x09, 0x4e, 0x6f, 0x63, 0x73, 0x79, 0x73,
	0x56, 0x72, 0x66, 0x12, 0x3a, 0x0a, 0x03, 0x76, 0x72, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x56,
	0x72, 0x66, 0x2e, 0x56, 0x72, 0x66, 0x42, 0x12, 0x82, 0x41, 0x0f, 0x2f, 0x6e, 0x6f, 0x63, 0x73,
	0x79, 0x73, 0x2d, 0x76, 0x72, 0x66, 0x2f, 0x76, 0x72, 0x66, 0x52, 0x03, 0x76, 0x72, 0x66, 0x1a,
	0xc9, 0x02, 0x0a, 0x03, 0x56, 0x72, 0x66, 0x12, 0x57, 0x0a, 0x08, 0x76, 0x72, 0x66, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x6f, 0x6e, 0x69,
	0x63, 0x2e, 0x4e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x56, 0x72, 0x66, 0x2e, 0x56, 0x72, 0x66, 0x2e,
	0x56, 0x72, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x42, 0x1b, 0x82, 0x41, 0x18, 0x2f,
	0x6e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x2d, 0x76, 0x72, 0x66, 0x2f, 0x76, 0x72, 0x66, 0x2f, 0x76,
	0x72, 0x66, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x07, 0x76, 0x72, 0x66, 0x4c, 0x69, 0x73, 0x74,
	0x1a, 0x60, 0x0a, 0x07, 0x56, 0x72, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x55, 0x0a, 0x08, 0x66,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x79, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x24, 0x82, 0x41, 0x21, 0x2f, 0x6e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x2d, 0x76,
	0x72, 0x66, 0x2f, 0x76, 0x72, 0x66, 0x2f, 0x76, 0x72, 0x66, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x2f,
	0x66, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x08, 0x66, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x1a, 0x86, 0x01, 0x0a, 0x0a, 0x56, 0x72, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65,
	0x79, 0x12, 0x3f, 0x0a, 0x08, 0x76, 0x72, 0x66, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x24, 0x82, 0x41, 0x21, 0x2f, 0x6e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x2d,
	0x76, 0x72, 0x66, 0x2f, 0x76, 0x72, 0x66, 0x2f, 0x76, 0x72, 0x66, 0x2d, 0x6c, 0x69, 0x73, 0x74,
	0x2f, 0x76, 0x72, 0x66, 0x2d, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x07, 0x76, 0x72, 0x66, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x76, 0x72, 0x66, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x4e, 0x6f, 0x63,
	0x73, 0x79, 0x73, 0x56, 0x72, 0x66, 0x2e, 0x56, 0x72, 0x66, 0x2e, 0x56, 0x72, 0x66, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x07, 0x76, 0x72, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x1b, 0x0a, 0x10, 0x63,
	0x6f, 0x6d, 0x2e, 0x6e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x5a,
	0x07, 0x2e, 0x3b, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nocsys_vrf_proto_rawDescOnce sync.Once
	file_nocsys_vrf_proto_rawDescData = file_nocsys_vrf_proto_rawDesc
)

func file_nocsys_vrf_proto_rawDescGZIP() []byte {
	file_nocsys_vrf_proto_rawDescOnce.Do(func() {
		file_nocsys_vrf_proto_rawDescData = protoimpl.X.CompressGZIP(file_nocsys_vrf_proto_rawDescData)
	})
	return file_nocsys_vrf_proto_rawDescData
}

var file_nocsys_vrf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nocsys_vrf_proto_goTypes = []interface{}{
	(*NocsysVrf)(nil),                // 0: sonic.NocsysVrf
	(*NocsysVrf_Vrf)(nil),            // 1: sonic.NocsysVrf.Vrf
	(*NocsysVrf_Vrf_VrfList)(nil),    // 2: sonic.NocsysVrf.Vrf.VrfList
	(*NocsysVrf_Vrf_VrfListKey)(nil), // 3: sonic.NocsysVrf.Vrf.VrfListKey
	(*ywrapper.BoolValue)(nil),       // 4: ywrapper.BoolValue
}
var file_nocsys_vrf_proto_depIdxs = []int32{
	1, // 0: sonic.NocsysVrf.vrf:type_name -> sonic.NocsysVrf.Vrf
	3, // 1: sonic.NocsysVrf.Vrf.vrf_list:type_name -> sonic.NocsysVrf.Vrf.VrfListKey
	4, // 2: sonic.NocsysVrf.Vrf.VrfList.fallback:type_name -> ywrapper.BoolValue
	2, // 3: sonic.NocsysVrf.Vrf.VrfListKey.vrf_list:type_name -> sonic.NocsysVrf.Vrf.VrfList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nocsys_vrf_proto_init() }
func file_nocsys_vrf_proto_init() {
	if File_nocsys_vrf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nocsys_vrf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NocsysVrf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nocsys_vrf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NocsysVrf_Vrf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nocsys_vrf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NocsysVrf_Vrf_VrfList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nocsys_vrf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NocsysVrf_Vrf_VrfListKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nocsys_vrf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nocsys_vrf_proto_goTypes,
		DependencyIndexes: file_nocsys_vrf_proto_depIdxs,
		MessageInfos:      file_nocsys_vrf_proto_msgTypes,
	}.Build()
	File_nocsys_vrf_proto = out.File
	file_nocsys_vrf_proto_rawDesc = nil
	file_nocsys_vrf_proto_goTypes = nil
	file_nocsys_vrf_proto_depIdxs = nil
}
