// openconfig.sonic_todo is generated by proto_generator as a protobuf
// representation of a YANG schema.
//
// Input schema modules:
//  - ../api/yang/sonic/sonic-platform.yang
//  - ../api/yang/sonic/sonic-interface.yang
//  - ../api/yang/sonic/sonic-port.yang
//  - ../api/yang/sonic/sonic-ntp.yang
//  - ../api/yang/sonic/sonic-vrf.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-interfaces.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-yang-types.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-inet-types.yang
//  - ../api/yang/sonic/third_party/ietf/iana-if-type.yang
//  - ../api/yang/sonic/sonic-loopback-interface.yang
//  - ../api/yang/sonic/sonic-platform-types.yang
//  - ../api/yang/sonic/sonic-neighbor.yang
//  - ../api/yang/sonic/sonic-route.yang
//  - ../api/yang/sonic/sonic-lldp.yang
//  - ../api/yang/sonic/sonic-vlan.yang
//  - ../api/yang/sonic/sonic-todo.yang
//  - ../api/yang/sonic/sonic-portchannel.yang
//  - ../api/yang/sonic/sonic-extension.yang
//  - ../api/yang/sonic/sonic-mirror-session.yang
//  - ../api/yang/sonic/sonic-vxlan.yang
//  - ../api/yang/sonic/sonic-fdb.yang
//  - ../api/yang/sonic/sonic-acl.yang
//  - ../api/yang/sonic/sonic-types.yang

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: sonic_todo.proto

package sonic

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/openconfig/ygot/proto/yext"
	ywrapper "github.com/openconfig/ygot/proto/ywrapper"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SonicTodo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todo *SonicTodo_Todo `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
}

func (x *SonicTodo) Reset() {
	*x = SonicTodo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sonic_todo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SonicTodo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SonicTodo) ProtoMessage() {}

func (x *SonicTodo) ProtoReflect() protoreflect.Message {
	mi := &file_sonic_todo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SonicTodo.ProtoReflect.Descriptor instead.
func (*SonicTodo) Descriptor() ([]byte, []int) {
	return file_sonic_todo_proto_rawDescGZIP(), []int{0}
}

func (x *SonicTodo) GetTodo() *SonicTodo_Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type SonicTodo_Todo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TodoList []*SonicTodo_Todo_TodoListKey `protobuf:"bytes,1,rep,name=todo_list,json=todoList,proto3" json:"todo_list,omitempty"`
}

func (x *SonicTodo_Todo) Reset() {
	*x = SonicTodo_Todo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sonic_todo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SonicTodo_Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SonicTodo_Todo) ProtoMessage() {}

func (x *SonicTodo_Todo) ProtoReflect() protoreflect.Message {
	mi := &file_sonic_todo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SonicTodo_Todo.ProtoReflect.Descriptor instead.
func (*SonicTodo_Todo) Descriptor() ([]byte, []int) {
	return file_sonic_todo_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SonicTodo_Todo) GetTodoList() []*SonicTodo_Todo_TodoListKey {
	if x != nil {
		return x.TodoList
	}
	return nil
}

type SonicTodo_Todo_TodoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Json *ywrapper.StringValue `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *SonicTodo_Todo_TodoList) Reset() {
	*x = SonicTodo_Todo_TodoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sonic_todo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SonicTodo_Todo_TodoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SonicTodo_Todo_TodoList) ProtoMessage() {}

func (x *SonicTodo_Todo_TodoList) ProtoReflect() protoreflect.Message {
	mi := &file_sonic_todo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SonicTodo_Todo_TodoList.ProtoReflect.Descriptor instead.
func (*SonicTodo_Todo_TodoList) Descriptor() ([]byte, []int) {
	return file_sonic_todo_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *SonicTodo_Todo_TodoList) GetJson() *ywrapper.StringValue {
	if x != nil {
		return x.Json
	}
	return nil
}

type SonicTodo_Todo_TodoListKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TodoList *SonicTodo_Todo_TodoList `protobuf:"bytes,2,opt,name=todo_list,json=todoList,proto3" json:"todo_list,omitempty"`
}

func (x *SonicTodo_Todo_TodoListKey) Reset() {
	*x = SonicTodo_Todo_TodoListKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sonic_todo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SonicTodo_Todo_TodoListKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SonicTodo_Todo_TodoListKey) ProtoMessage() {}

func (x *SonicTodo_Todo_TodoListKey) ProtoReflect() protoreflect.Message {
	mi := &file_sonic_todo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SonicTodo_Todo_TodoListKey.ProtoReflect.Descriptor instead.
func (*SonicTodo_Todo_TodoListKey) Descriptor() ([]byte, []int) {
	return file_sonic_todo_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *SonicTodo_Todo_TodoListKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SonicTodo_Todo_TodoListKey) GetTodoList() *SonicTodo_Todo_TodoList {
	if x != nil {
		return x.TodoList
	}
	return nil
}

var File_sonic_todo_proto protoreflect.FileDescriptor

var file_sonic_todo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x5f, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x1a, 0x0e, 0x79, 0x77, 0x72, 0x61, 0x70,
	0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x79, 0x65, 0x78, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x03, 0x0a, 0x09, 0x53, 0x6f, 0x6e, 0x69, 0x63, 0x54,
	0x6f, 0x64, 0x6f, 0x12, 0x3e, 0x0a, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x53, 0x6f, 0x6e, 0x69, 0x63, 0x54,
	0x6f, 0x64, 0x6f, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x42, 0x13, 0x82, 0x41, 0x10, 0x2f, 0x73, 0x6f,
	0x6e, 0x69, 0x63, 0x2d, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x52, 0x04, 0x74,
	0x6f, 0x64, 0x6f, 0x1a, 0xc5, 0x02, 0x0a, 0x04, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x5d, 0x0a, 0x09,
	0x74, 0x6f, 0x64, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x53, 0x6f, 0x6e, 0x69, 0x63, 0x54, 0x6f, 0x64,
	0x6f, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x4b,
	0x65, 0x79, 0x42, 0x1d, 0x82, 0x41, 0x1a, 0x2f, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2d, 0x74, 0x6f,
	0x64, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2d, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x08, 0x74, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x59, 0x0a, 0x08, 0x54,
	0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x4d, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x79, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x22, 0x82, 0x41,
	0x1f, 0x2f, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2d, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x74, 0x6f, 0x64,
	0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x6a, 0x73, 0x6f, 0x6e,
	0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x1a, 0x82, 0x01, 0x0a, 0x0b, 0x54, 0x6f, 0x64, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x22, 0x82, 0x41, 0x1f, 0x2f, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2d,
	0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2d, 0x6c,
	0x69, 0x73, 0x74, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3b,
	0x0a, 0x09, 0x74, 0x6f, 0x64, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x53, 0x6f, 0x6e, 0x69, 0x63, 0x54,
	0x6f, 0x64, 0x6f, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x08, 0x74, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x1b, 0x0a, 0x10, 0x63,
	0x6f, 0x6d, 0x2e, 0x6e, 0x6f, 0x63, 0x73, 0x79, 0x73, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x5a,
	0x07, 0x2e, 0x3b, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sonic_todo_proto_rawDescOnce sync.Once
	file_sonic_todo_proto_rawDescData = file_sonic_todo_proto_rawDesc
)

func file_sonic_todo_proto_rawDescGZIP() []byte {
	file_sonic_todo_proto_rawDescOnce.Do(func() {
		file_sonic_todo_proto_rawDescData = protoimpl.X.CompressGZIP(file_sonic_todo_proto_rawDescData)
	})
	return file_sonic_todo_proto_rawDescData
}

var file_sonic_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sonic_todo_proto_goTypes = []interface{}{
	(*SonicTodo)(nil),                  // 0: sonic.SonicTodo
	(*SonicTodo_Todo)(nil),             // 1: sonic.SonicTodo.Todo
	(*SonicTodo_Todo_TodoList)(nil),    // 2: sonic.SonicTodo.Todo.TodoList
	(*SonicTodo_Todo_TodoListKey)(nil), // 3: sonic.SonicTodo.Todo.TodoListKey
	(*ywrapper.StringValue)(nil),       // 4: ywrapper.StringValue
}
var file_sonic_todo_proto_depIdxs = []int32{
	1, // 0: sonic.SonicTodo.todo:type_name -> sonic.SonicTodo.Todo
	3, // 1: sonic.SonicTodo.Todo.todo_list:type_name -> sonic.SonicTodo.Todo.TodoListKey
	4, // 2: sonic.SonicTodo.Todo.TodoList.json:type_name -> ywrapper.StringValue
	2, // 3: sonic.SonicTodo.Todo.TodoListKey.todo_list:type_name -> sonic.SonicTodo.Todo.TodoList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sonic_todo_proto_init() }
func file_sonic_todo_proto_init() {
	if File_sonic_todo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sonic_todo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SonicTodo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sonic_todo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SonicTodo_Todo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sonic_todo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SonicTodo_Todo_TodoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sonic_todo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SonicTodo_Todo_TodoListKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sonic_todo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sonic_todo_proto_goTypes,
		DependencyIndexes: file_sonic_todo_proto_depIdxs,
		MessageInfos:      file_sonic_todo_proto_msgTypes,
	}.Build()
	File_sonic_todo_proto = out.File
	file_sonic_todo_proto_rawDesc = nil
	file_sonic_todo_proto_goTypes = nil
	file_sonic_todo_proto_depIdxs = nil
}
