// openconfig.sonic_neighor is generated by proto_generator as a protobuf
// representation of a YANG schema.
//
// Input schema modules:
//  - ../api/yang/sonic/sonic-platform.yang
//  - ../api/yang/sonic/sonic-interface.yang
//  - ../api/yang/sonic/sonic-port.yang
//  - ../api/yang/sonic/sonic-ntp.yang
//  - ../api/yang/sonic/sonic-vrf.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-interfaces.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-yang-types.yang
//  - ../api/yang/sonic/third_party/ietf/ietf-inet-types.yang
//  - ../api/yang/sonic/third_party/ietf/iana-if-type.yang
//  - ../api/yang/sonic/sonic-loopback-interface.yang
//  - ../api/yang/sonic/sonic-platform-types.yang
//  - ../api/yang/sonic/sonic-neighbor.yang
//  - ../api/yang/sonic/sonic-route.yang
//  - ../api/yang/sonic/sonic-lldp.yang
//  - ../api/yang/sonic/sonic-vlan.yang
//  - ../api/yang/sonic/sonic-todo.yang
//  - ../api/yang/sonic/sonic-portchannel.yang
//  - ../api/yang/sonic/sonic-extension.yang
//  - ../api/yang/sonic/sonic-mirror-session.yang
//  - ../api/yang/sonic/sonic-vxlan.yang
//  - ../api/yang/sonic/sonic-fdb.yang
//  - ../api/yang/sonic/sonic-acl.yang
//  - ../api/yang/sonic/sonic-types.yang

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: sonic_neighor.proto

package sonic

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/openconfig/ygot/proto/yext"
	ywrapper "github.com/openconfig/ygot/proto/ywrapper"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SonicNeighor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Neighor *SonicNeighor_Neighor `protobuf:"bytes,1,opt,name=neighor,proto3" json:"neighor,omitempty"`
}

func (x *SonicNeighor) Reset() {
	*x = SonicNeighor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sonic_neighor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SonicNeighor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SonicNeighor) ProtoMessage() {}

func (x *SonicNeighor) ProtoReflect() protoreflect.Message {
	mi := &file_sonic_neighor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SonicNeighor.ProtoReflect.Descriptor instead.
func (*SonicNeighor) Descriptor() ([]byte, []int) {
	return file_sonic_neighor_proto_rawDescGZIP(), []int{0}
}

func (x *SonicNeighor) GetNeighor() *SonicNeighor_Neighor {
	if x != nil {
		return x.Neighor
	}
	return nil
}

type SonicNeighor_Neighor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NeighorList []*SonicNeighor_Neighor_NeighorListKey `protobuf:"bytes,1,rep,name=neighor_list,json=neighorList,proto3" json:"neighor_list,omitempty"`
}

func (x *SonicNeighor_Neighor) Reset() {
	*x = SonicNeighor_Neighor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sonic_neighor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SonicNeighor_Neighor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SonicNeighor_Neighor) ProtoMessage() {}

func (x *SonicNeighor_Neighor) ProtoReflect() protoreflect.Message {
	mi := &file_sonic_neighor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SonicNeighor_Neighor.ProtoReflect.Descriptor instead.
func (*SonicNeighor_Neighor) Descriptor() ([]byte, []int) {
	return file_sonic_neighor_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SonicNeighor_Neighor) GetNeighorList() []*SonicNeighor_Neighor_NeighorListKey {
	if x != nil {
		return x.NeighorList
	}
	return nil
}

type SonicNeighor_Neighor_NeighorList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Neigh *ywrapper.StringValue `protobuf:"bytes,1,opt,name=neigh,proto3" json:"neigh,omitempty"`
}

func (x *SonicNeighor_Neighor_NeighorList) Reset() {
	*x = SonicNeighor_Neighor_NeighorList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sonic_neighor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SonicNeighor_Neighor_NeighorList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SonicNeighor_Neighor_NeighorList) ProtoMessage() {}

func (x *SonicNeighor_Neighor_NeighorList) ProtoReflect() protoreflect.Message {
	mi := &file_sonic_neighor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SonicNeighor_Neighor_NeighorList.ProtoReflect.Descriptor instead.
func (*SonicNeighor_Neighor_NeighorList) Descriptor() ([]byte, []int) {
	return file_sonic_neighor_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *SonicNeighor_Neighor_NeighorList) GetNeigh() *ywrapper.StringValue {
	if x != nil {
		return x.Neigh
	}
	return nil
}

type SonicNeighor_Neighor_NeighorListKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IpPrefix    string                            `protobuf:"bytes,2,opt,name=ip_prefix,json=ipPrefix,proto3" json:"ip_prefix,omitempty"`
	NeighorList *SonicNeighor_Neighor_NeighorList `protobuf:"bytes,3,opt,name=neighor_list,json=neighorList,proto3" json:"neighor_list,omitempty"`
}

func (x *SonicNeighor_Neighor_NeighorListKey) Reset() {
	*x = SonicNeighor_Neighor_NeighorListKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sonic_neighor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SonicNeighor_Neighor_NeighorListKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SonicNeighor_Neighor_NeighorListKey) ProtoMessage() {}

func (x *SonicNeighor_Neighor_NeighorListKey) ProtoReflect() protoreflect.Message {
	mi := &file_sonic_neighor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SonicNeighor_Neighor_NeighorListKey.ProtoReflect.Descriptor instead.
func (*SonicNeighor_Neighor_NeighorListKey) Descriptor() ([]byte, []int) {
	return file_sonic_neighor_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *SonicNeighor_Neighor_NeighorListKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SonicNeighor_Neighor_NeighorListKey) GetIpPrefix() string {
	if x != nil {
		return x.IpPrefix
	}
	return ""
}

func (x *SonicNeighor_Neighor_NeighorListKey) GetNeighorList() *SonicNeighor_Neighor_NeighorList {
	if x != nil {
		return x.NeighorList
	}
	return nil
}

var File_sonic_neighor_proto protoreflect.FileDescriptor

var file_sonic_neighor_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x5f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x1a, 0x0e, 0x79, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x79, 0x65,
	0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x04, 0x0a, 0x0c, 0x53, 0x6f, 0x6e,
	0x69, 0x63, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x12, 0x50, 0x0a, 0x07, 0x6e, 0x65, 0x69,
	0x67, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x6f, 0x6e,
	0x69, 0x63, 0x2e, 0x53, 0x6f, 0x6e, 0x69, 0x63, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2e,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x42, 0x19, 0x82, 0x41, 0x16, 0x2f, 0x73, 0x6f, 0x6e,
	0x69, 0x63, 0x2d, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x6f, 0x72, 0x52, 0x07, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x1a, 0xd9, 0x03, 0x0a, 0x07,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x12, 0x75, 0x0a, 0x0c, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x6f, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e,
	0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x53, 0x6f, 0x6e, 0x69, 0x63, 0x4e, 0x65, 0x69, 0x67, 0x68,
	0x6f, 0x72, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68,
	0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x42, 0x26, 0x82, 0x41, 0x23, 0x2f, 0x73,
	0x6f, 0x6e, 0x69, 0x63, 0x2d, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69,
	0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2d, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x0b, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x68,
	0x0a, 0x0b, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x59, 0x0a,
	0x05, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x79,
	0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x2c, 0x82, 0x41, 0x29, 0x2f, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2d, 0x6e,
	0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e,
	0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x6e, 0x65, 0x69, 0x67,
	0x68, 0x52, 0x05, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x1a, 0xec, 0x01, 0x0a, 0x0e, 0x4e, 0x65, 0x69,
	0x67, 0x68, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x3f, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x2b, 0x82, 0x41, 0x28, 0x2f, 0x73,
	0x6f, 0x6e, 0x69, 0x63, 0x2d, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69,
	0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2d, 0x6c, 0x69, 0x73,
	0x74, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4d, 0x0a, 0x09,
	0x69, 0x70, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x30, 0x82, 0x41, 0x2d, 0x2f, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2d, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2f, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x6f, 0x72, 0x2d, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x69, 0x70, 0x2d, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x52, 0x08, 0x69, 0x70, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x4a, 0x0a, 0x0c, 0x6e,
	0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x53, 0x6f, 0x6e, 0x69, 0x63, 0x4e,
	0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x2e, 0x4e,
	0x65, 0x69, 0x67, 0x68, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0b, 0x6e, 0x65, 0x69, 0x67,
	0x68, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x1b, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x6e,
	0x6f, 0x63, 0x73, 0x79, 0x73, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x5a, 0x07, 0x2e, 0x3b, 0x73,
	0x6f, 0x6e, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sonic_neighor_proto_rawDescOnce sync.Once
	file_sonic_neighor_proto_rawDescData = file_sonic_neighor_proto_rawDesc
)

func file_sonic_neighor_proto_rawDescGZIP() []byte {
	file_sonic_neighor_proto_rawDescOnce.Do(func() {
		file_sonic_neighor_proto_rawDescData = protoimpl.X.CompressGZIP(file_sonic_neighor_proto_rawDescData)
	})
	return file_sonic_neighor_proto_rawDescData
}

var file_sonic_neighor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sonic_neighor_proto_goTypes = []interface{}{
	(*SonicNeighor)(nil),                        // 0: sonic.SonicNeighor
	(*SonicNeighor_Neighor)(nil),                // 1: sonic.SonicNeighor.Neighor
	(*SonicNeighor_Neighor_NeighorList)(nil),    // 2: sonic.SonicNeighor.Neighor.NeighorList
	(*SonicNeighor_Neighor_NeighorListKey)(nil), // 3: sonic.SonicNeighor.Neighor.NeighorListKey
	(*ywrapper.StringValue)(nil),                // 4: ywrapper.StringValue
}
var file_sonic_neighor_proto_depIdxs = []int32{
	1, // 0: sonic.SonicNeighor.neighor:type_name -> sonic.SonicNeighor.Neighor
	3, // 1: sonic.SonicNeighor.Neighor.neighor_list:type_name -> sonic.SonicNeighor.Neighor.NeighorListKey
	4, // 2: sonic.SonicNeighor.Neighor.NeighorList.neigh:type_name -> ywrapper.StringValue
	2, // 3: sonic.SonicNeighor.Neighor.NeighorListKey.neighor_list:type_name -> sonic.SonicNeighor.Neighor.NeighorList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sonic_neighor_proto_init() }
func file_sonic_neighor_proto_init() {
	if File_sonic_neighor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sonic_neighor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SonicNeighor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sonic_neighor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SonicNeighor_Neighor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sonic_neighor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SonicNeighor_Neighor_NeighorList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sonic_neighor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SonicNeighor_Neighor_NeighorListKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sonic_neighor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sonic_neighor_proto_goTypes,
		DependencyIndexes: file_sonic_neighor_proto_depIdxs,
		MessageInfos:      file_sonic_neighor_proto_msgTypes,
	}.Build()
	File_sonic_neighor_proto = out.File
	file_sonic_neighor_proto_rawDesc = nil
	file_sonic_neighor_proto_goTypes = nil
	file_sonic_neighor_proto_depIdxs = nil
}
